### ISSUE TITLE
can you make this a chrome extension or a windows.exe 

### ISSUE THREAD

**Issue by Droyk** [asvd/dragscroll#25]
Hey developer I really like drag and scroll type of scrolling plz can you make this available on windows 10 too means an .exe would be suffice or a minimum a chrome extension plz

**Comment by asvd** [comment]
What should it do then?

**Comment by Droyk** [comment]
What do you mean "what should do it do then?"
it will drag and scroll obviously that what it does & that why you created this right.

**Comment by asvd** [comment]
you mean, you want this to happen for all applications in your system, after you launch that .exe?

**Comment by Droyk** [comment]
Yup

**Comment by Droyk** [comment]
>you mean, you want this to happen for all applications in your system, after you launch that .exe?

Yup & from your question it seem like it isn't really possible to do that am I really asking for too much?

**Comment by asvd** [comment]
Not exactly, this is just a little bit different thing. The idea you describe is a subject for a separate application designed for end-users, which should be implemented using different technology. I do not know much about windows applications, but there might be something like that implemented already. Dragscroll cannot be reused for that purpose, since it is web-based and can only work in a browser.

Besides, it is designed not for users, but for developers who might wish to add such a feature in particular cases. It is theoretically possible to convert it into a plugin for Google Chrome, but I will not find time do that as well.

**Comment by Droyk** [comment]
pity :(
